#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

link="https://www.youtube.com/watch?v=mC-zw0zCCtg"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sudo sed -i "s#server_name _;#$new_conf#" /etc/nginx/sites-enabled/default

sudo service nginx restart
