#!/usr/bin/env bash
#SSH client configuration must be configured to refuse to authenticate using a password

Host 18.209.178.16
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
